Repository hmcts/ethos-repl-docmosis-service, pull requests merged in 2019-10, with the labels that each got.

#412 Bump java chart version
  charts/ethos-repl-docmosis-backend/Chart.yaml
  charts/ethos-repl-docmosis-backend/requirements.yaml
Labels: ns:ethos-repl-docmosis-backend-pr-412

#429 Disable ASE and enable it only for DEMO
  infrastructure/demo.tfvars
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:ethos-repl-docmosis-backend-pr-429

#426 Create submultiples added for Eng and Scot
  .gitignore
  src/test/functional/java/uk/gov/hmcts/ethos/replacement/functional/bulk/CreateBulkComponentTest.java
  src/test/functional/java/uk/gov/hmcts/ethos/replacement/functional/bulk/CreateSubMultipleComponentTest.java
  src/test/functional/java/uk/gov/hmcts/ethos/replacement/functional/bulk/DeleteSubMultipleComponentTest.java
  src/test/functional/java/uk/gov/hmcts/ethos/replacement/functional/bulk/SearchBulkComponentTest.java
  src/test/functional/java/uk/gov/hmcts/ethos/replacement/functional/bulk/UpdateBulkComponentTest.java
  src/test/functional/java/uk/gov/hmcts/ethos/replacement/functional/bulk/UpdateCaseBulkComponentTest.java
  src/test/functional/java/uk/gov/hmcts/ethos/replacement/functional/bulk/UpdateSubMultipleComponentTest.java
  src/test/functional/java/uk/gov/hmcts/ethos/replacement/functional/util/Constants.java
  src/test/functional/java/uk/gov/hmcts/ethos/replacement/functional/util/ResponseUtil.java
  src/test/functional/java/uk/gov/hmcts/ethos/replacement/functional/util/TestUtil.java
  src/test/functional/resources/testData/bulk/createSubMultipleDetailsEng1.json
  src/test/functional/resources/testData/bulk/deleteSubMultipleDetailsEng1.json
  src/test/functional/resources/testData/bulk/updateSubMultipleDetailsEng1.json
Labels: ns:ethos-repl-docmosis-backend-pr-426

#433 Add dependabot config
  .dependabot/config.yml
Labels: ns:ethos-repl-docmosis-backend-pr-433

#439 Bump health starter
  build.gradle
Labels: ns:ethos-repl-docmosis-backend-pr-439

#448 adde suppressions
  dependency-check-suppressions.xml
Labels: ns:ethos-repl-docmosis-backend-pr-448
