Repository hmcts/ethos-repl-docmosis-service, pull requests merged in 2022-09, with the labels that each got.

#1916 Ecm 610
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/refdatafixes/CreateController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/refdatafixes/ReferenceDataFixesController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/CallbackRespHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/refdatafixes/CreateService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/refdatafixes/RefDataFixesCcdDataSource.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/refdatafixes/RefDataFixesDataSource.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/refdatafixes/RefDataFixesElasticSearchQuery.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/refdatafixes/RefDataFixesException.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/refdatafixes/ReferenceDataFixesService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/refdatafixes/refData/AdminData.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/refdatafixes/refData/AdminDetails.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/refdatafixes/refData/CCDAdminCallbackResponse.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/refdatafixes/refData/CCDAdminRequest.java
  src/main/resources/sqlscripts/fn_ethosCaseRefGen.sql
  src/main/resources/sqlscripts/fn_ethosCaseRefGenPT.sql
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CreateControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ReferenceDataFixesControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/refdatafixeshelper/RefDataFixesCcdDataSourceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CreateServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ReferenceDataFixesServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/AdminDataBuilder.java
Labels: ns:ethos, prd:ethos, rel:ethos-repl-docmosis-backend-pr-1916

#1919 Snakeyaml CVE fix
  build.gradle
Labels: ns:ethos, prd:ethos, rel:ethos-repl-docmosis-backend-pr-1919

#1927 [ECM-922]-Fortify Crossbrowser fix
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  src/test/config.js
  src/test/end-to-end/helpers/SauceLabsReportingHelper.js
  src/test/end-to-end/pages/IDAM/signIn.js
  src/test/end-to-end/paths/verifyBFActionOutstandingError.js
  src/test/end-to-end/paths/verifyCaseDetails.js
  src/test/end-to-end/saucelabs.conf.js
Labels: ns:ethos, prd:ethos, ecm-support, rel:ethos-repl-docmosis-backend-pr-1927

#1935 [ECM-943]-Dependency Check Fix
  build.gradle
Labels: ns:ethos, prd:ethos, dependency-check-fix, rel:ethos-repl-docmosis-backend-pr-1935

#1933 Remove postgresql v11
  charts/ethos-repl-docmosis-backend/Chart.yaml
  charts/ethos-repl-docmosis-backend/values.yaml
  infrastructure/main.tf
  infrastructure/modules.tf
Labels: ns:ethos, prd:ethos, destroy, rel:ethos-repl-docmosis-backend-pr-1933

#1918 R5.0.38
  build.gradle
  package.json
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/refdatafixes/CreateController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/refdatafixes/ReferenceDataFixesController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/CallbackRespHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/refdatafixes/CreateService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/refdatafixes/RefDataFixesCcdDataSource.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/refdatafixes/RefDataFixesDataSource.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/refdatafixes/RefDataFixesElasticSearchQuery.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/refdatafixes/RefDataFixesException.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/refdatafixes/ReferenceDataFixesService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/refdatafixes/refData/AdminData.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/refdatafixes/refData/AdminDetails.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/refdatafixes/refData/CCDAdminCallbackResponse.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/refdatafixes/refData/CCDAdminRequest.java
  src/main/resources/sqlscripts/fn_ethosCaseRefGen.sql
  src/main/resources/sqlscripts/fn_ethosCaseRefGenPT.sql
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CreateControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ReferenceDataFixesControllerTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/refdatafixeshelper/RefDataFixesCcdDataSourceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CreateServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ReferenceDataFixesServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/utils/AdminDataBuilder.java
  yarn.lock
Labels: ns:ethos, prd:ethos, rel:ethos-repl-docmosis-backend-pr-1918

#1938 Venue Address change Nottingham Midlands East
  src/main/resources/venueAddressValues.xlsx
Labels: ns:ethos, prd:ethos, rel:ethos-repl-docmosis-backend-pr-1938
