Repository hmcts/ethos-repl-docmosis-service, pull requests merged in 2022-11, with the labels that each got.

#1966 Update Jenkinsfile_CNP
  Jenkinsfile_CNP
Labels: ns:ethos, prd:ethos, rel:ethos-repl-docmosis-backend-pr-1966

#1967 CVE fixed
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ethos, prd:ethos, rel:ethos-repl-docmosis-backend-pr-1967

#1968 [ECM-1007]-Execute ECM Functional Tests on ExUI Environment
  Jenkinsfile_nightly
  src/test/config.js
Labels: ns:ethos, prd:ethos, ecm-automation-phase2, ecm-support, rel:ethos-repl-docmosis-backend-pr-1968

#1970 Added security context for fortify
  src/kubernetes/deployment.template.yaml
Labels: ns:ethos, prd:ethos, rel:ethos-repl-docmosis-backend-pr-1970

#1971 ECM-1020 - Bulk add change
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/multiples/bulkaddsingles/SingleCasesValidator.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/multiples/bulkaddsingles/SingleCasesValidatorTest.java
Labels: ns:ethos, prd:ethos, rel:ethos-repl-docmosis-backend-pr-1971

#1972 deleted file
  src/kubernetes/deployment.template.yaml
Labels: ns:ethos, prd:ethos, rel:ethos-repl-docmosis-backend-pr-1972

#1973 [ECM-1026]-IDAM And S2S Helpers Update Using CodeceptJS RestApi
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  package.json
  src/test/config.js
  src/test/end-to-end/codecept.conf.js
  src/test/end-to-end/helpers/idamApi.js
  src/test/end-to-end/helpers/s2sHelper.js
  src/test/end-to-end/paths/verifyAcceptCase.js
  yarn.lock
Labels: ns:ethos, prd:ethos, ecm-automation-phase2, rel:ethos-repl-docmosis-backend-pr-1973

#1974 [ECM-976]-Crossbrowser Fix
  build.gradle
  config/owasp/suppressions.xml
  package.json
  src/test/config.js
  src/test/end-to-end/helpers/JSWait.js
  src/test/end-to-end/pages/IDAM/signIn.js
  src/test/end-to-end/paths/verifyCaseDetails.js
  src/test/end-to-end/saucelabs.conf.js
  yarn.lock
Labels: ns:ethos, prd:ethos, ecm-automation-phase2, rel:ethos-repl-docmosis-backend-pr-1974

#1975 ECM-952
  build.gradle
Labels: ns:ethos, prd:ethos, rel:ethos-repl-docmosis-backend-pr-1975

#1979 [ECM-1030]-Add Hooks To ECM Automation Framework
  package.json
  src/test/config.js
  src/test/end-to-end/codecept.conf.js
  src/test/end-to-end/helpers/caseHelper.js
  src/test/end-to-end/helpers/idamApi.js
  src/test/end-to-end/helpers/s2sHelper.js
  src/test/end-to-end/pages/common/constants.js
  src/test/end-to-end/paths/createLeedsMultiples.js
  src/test/end-to-end/paths/crossBrowserTests.js
  src/test/end-to-end/paths/verifyAcceptCase.js
  src/test/end-to-end/paths/verifyCaseClose.js
  src/test/end-to-end/paths/verifyCaseDetails.js
  src/test/end-to-end/paths/verifyECMCase.js
  yarn.lock
Labels: ns:ethos, prd:ethos, rel:ethos-repl-docmosis-backend-pr-1979

#1981 ECM-759
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/ExcelReadingService.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleBatchUpdate2Service.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleUploadService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/ExcelReadingServiceTest.java
Labels: ns:ethos, prd:ethos, rel:ethos-repl-docmosis-backend-pr-1981
