Repository hmcts/ethos-repl-docmosis-service, pull requests merged in 2022-08, with the labels that each got.

#1888 Update suppressions.xml
  config/owasp/suppressions.xml
Labels: ns:ethos, prd:ethos, rel:ethos-repl-docmosis-backend-pr-1888

#1890 Fix CVEs
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ethos, prd:ethos, rel:ethos-repl-docmosis-backend-pr-1890

#1892 dependencies update
  build.gradle
Labels: ns:ethos, prd:ethos, rel:ethos-repl-docmosis-backend-pr-1892

#1893 Fortify fixes
  docker/app.yml
Labels: ns:ethos, prd:ethos, rel:ethos-repl-docmosis-backend-pr-1893

#1894 [ECM-892]-BF Actions Failure Test fix
  src/test/end-to-end/pages/acceptanceCase/acceptCase.js
  src/test/end-to-end/pages/broughtForward/bfActionsOutstandingError.js
Labels: ns:ethos, prd:ethos, ecm-automation, ecm-support, rel:ethos-repl-docmosis-backend-pr-1894

#1897 [ECM-898]-Crossbrowser Tests fix
  Jenkinsfile_nightly
Labels: ns:ethos, prd:ethos, ecm-support, rel:ethos-repl-docmosis-backend-pr-1897

#1898 [ECM-897]-Upload Document E2E
  src/test/end-to-end/data/commonConfig.json
  src/test/end-to-end/data/fileUpload.txt
  src/test/end-to-end/helpers/caseHelper.js
  src/test/end-to-end/pages/caseTransfer/caseTransfer.js
  src/test/end-to-end/pages/common/constants.js
  src/test/end-to-end/pages/steps.js
  src/test/end-to-end/pages/uploadDocument/uploadDocument.js
  src/test/end-to-end/paths/verifyUploadDocument.js
Labels: ns:ethos, prd:ethos, ecm-automation-phase2, rel:ethos-repl-docmosis-backend-pr-1898

#1899 ECM-899, cases in submitted state can be bulk added to multiples as well
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/multiples/bulkaddsingles/SingleCasesValidator.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/multiples/bulkaddsingles/SingleCasesValidatorTest.java
Labels: ns:ethos, prd:ethos, rel:ethos-repl-docmosis-backend-pr-1899

#1903 dependencies update
  build.gradle
Labels: ns:ethos, prd:ethos, rel:ethos-repl-docmosis-backend-pr-1903

#1912 Bump dependencies
  build.gradle
Labels: ns:ethos, prd:ethos, rel:ethos-repl-docmosis-backend-pr-1912

#1911 Add backstage configuration file
  catalog-info.yaml
Labels: ns:ethos, prd:ethos, rel:ethos-repl-docmosis-backend-pr-1911
