Repository hmcts/ethos-repl-docmosis-service, pull requests merged in 2022-06, with the labels that each got.

#1825 ECM-788 implemented
  build.gradle
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/FlagsImageHelper.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerServiceTest.java
  src/test/resources/caseDetailsTest13.json
  src/test/resources/caseDetailsTest14.json
  src/test/resources/caseDetailsTest15.json
Labels: ns:ethos, prd:ethos, rel:ethos-repl-docmosis-backend-pr-1825

#1827 ecm common version update
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ethos, prd:ethos, rel:ethos-repl-docmosis-backend-pr-1827

#1803 R5.0.31
  build.gradle
  charts/ethos-repl-docmosis-backend/Chart.yaml
  charts/ethos-repl-docmosis-backend/values.yaml
  config/owasp/suppressions.xml
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ListingGenerationController.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/FlagsImageHelper.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/letters/InvalidCharacterCheck.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/multiples/bulkaddsingles/BulkAddSinglesValidator.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/multiples/bulkaddsingles/SingleCasesValidator.java
  src/test/end-to-end/data/commonConfig.json
  src/test/end-to-end/helpers/caseHelper.js
  src/test/end-to-end/pages/common/constants.js
  src/test/end-to-end/pages/createReport/createReport.js
  src/test/end-to-end/pages/steps.js
  src/test/end-to-end/paths/verifyCreateReport.js
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/letters/InvalidCharacterCheckTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CaseManagementForCaseWorkerServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ListingServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ReferenceServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/multiples/bulkaddsingles/BulkAddSinglesValidatorTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/multiples/bulkaddsingles/SingleCasesValidatorTest.java
  src/test/resources/caseDetailsTest13.json
  src/test/resources/caseDetailsTest14.json
  src/test/resources/caseDetailsTest15.json
Labels: ns:ethos, prd:ethos, rel:ethos-repl-docmosis-backend-pr-1803

#1829 DocStore true
  charts/ethos-repl-docmosis-backend/Chart.yaml
  charts/ethos-repl-docmosis-backend/values.yaml
Labels: ns:ethos, prd:ethos, rel:ethos-repl-docmosis-backend-pr-1829

#1830 [ECM-707]-Future Date Check On Hearing Page
  src/test/end-to-end/data/commonConfig.json
  src/test/end-to-end/helpers/caseHelper.js
  src/test/end-to-end/pages/hearingDetails/updateHearingDetails.js
  src/test/end-to-end/pages/steps.js
  src/test/end-to-end/paths/validateFutureDateCheckOnHearingDetails.js
Labels: ns:ethos, prd:ethos, ecm-automation-phase2, rel:ethos-repl-docmosis-backend-pr-1830

#1834 [ECM-707]-Future Date check validation
  src/test/end-to-end/data/commonConfig.json
  src/test/end-to-end/pages/hearingDetails/updateHearingDetails.js
  src/test/end-to-end/paths/verifyFutureDateCheckOnTheHearingDetailsPage.js
Labels: ns:ethos, prd:ethos, ecm-automation-phase2, rel:ethos-repl-docmosis-backend-pr-1834

#1820 ECM-759
  build.gradle
  charts/ethos-repl-docmosis-backend/Chart.yaml
  charts/ethos-repl-docmosis-backend/values.yaml
  config/owasp/suppressions.xml
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/UpdateDataModelBuilder.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleBatchUpdate2Service.java
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleUploadService.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/UpdateDataModelBuilderTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/excel/MultipleUploadServiceTest.java
Labels: ns:ethos, prd:ethos, rel:ethos-repl-docmosis-backend-pr-1820

#1845 [ECM-713] Move Accepted Case to Case Closed state error check
  src/test/end-to-end/codecept.conf.js
  src/test/end-to-end/data/commonConfig.json
  src/test/end-to-end/helpers/caseHelper.js
  src/test/end-to-end/pages/IDAM/signIn.js
  src/test/end-to-end/pages/acceptanceCase/acceptCase.js
  src/test/end-to-end/pages/acceptanceCase/rejectCase.js
  src/test/end-to-end/pages/amendCaseDetails/amendCaseDetails.js
  src/test/end-to-end/pages/amendCaseDetails/amendCaseDetailsWithCasePosition.js
  src/test/end-to-end/pages/amendClaimantDetails/amendClaimantDetails.js
  src/test/end-to-end/pages/amendClaimantRepresentative/amendClaimantRepresentative.js
  src/test/end-to-end/pages/amendHearing/addAmendHearing.js
  src/test/end-to-end/pages/amendJudgment/addAmendJudgment.js
  src/test/end-to-end/pages/amendJurisdiction/addAmendJurisdiction.js
  src/test/end-to-end/pages/amendRespondentDetails/amendRespondentDetails.js
  src/test/end-to-end/pages/amendRespondentRepresentative/amendRespondentRepresentative.js
  src/test/end-to-end/pages/broughtForward/broughtForward.js
  src/test/end-to-end/pages/createReport/createReport.js
  src/test/end-to-end/pages/desposeCase/desposeCase.js
  src/test/end-to-end/pages/fixCaseApi/fixCaseApi.js
  src/test/end-to-end/pages/generateCorrespondence/generateCorrespondence.js
  src/test/end-to-end/pages/hearingDetails/updateHearingDetails.js
  src/test/end-to-end/pages/nextStep/nextStep.js
  src/test/end-to-end/pages/printHearingLists/printHearingLists.js
  src/test/end-to-end/pages/restrictedCases/restrictedCases.js
  src/test/end-to-end/pages/steps.js
  src/test/end-to-end/paths/moveAcceptedCaseToCaseCloseStateErrorCheck.js
  src/test/end-to-end/paths/moveRejectCaseToCaseCloseStateErrorCheck.js
  src/test/end-to-end/paths/moveSubmittedCaseToCaseCloseErrorCheck.js
  src/test/end-to-end/paths/verifyRejectCase.js
Labels: ns:ethos, prd:ethos, ecm-automation-phase2, rel:ethos-repl-docmosis-backend-pr-1845

#1848 ECM-829
  src/main/resources/venueAddressValues.xlsx
Labels: ns:ethos, prd:ethos, rel:ethos-repl-docmosis-backend-pr-1848

#1853 yarn update
  package.json
  yarn.lock
Labels: ns:ethos, prd:ethos, rel:ethos-repl-docmosis-backend-pr-1853

#1852 [ECM-717]-Validate Hearing Error Message In Weekend
  src/test/end-to-end/data/commonConfig.json
  src/test/end-to-end/helpers/caseHelper.js
  src/test/end-to-end/helpers/utils.js
  src/test/end-to-end/pages/amendHearing/hearingListedInWeekend.js
  src/test/end-to-end/pages/steps.js
  src/test/end-to-end/paths/validateHearingListedErrorMsgInWeekend.js
Labels: ns:ethos, prd:ethos, ecm-automation-phase2, rel:ethos-repl-docmosis-backend-pr-1852

#1855 address change
  src/main/resources/venueAddressValues.xlsx
Labels: ns:ethos, prd:ethos, rel:ethos-repl-docmosis-backend-pr-1855

#1858 Ecm 829 address change and bump versions
  build.gradle
  package.json
  src/main/resources/venueAddressValues.xlsx
  yarn.lock
Labels: ns:ethos, prd:ethos, rel:ethos-repl-docmosis-backend-pr-1858

#1860 [ECM-701] Test code clean up activity
  src/test/end-to-end/helpers/caseHelper.js
  src/test/end-to-end/pages/createCase/createCase.js
  src/test/end-to-end/pages/createCase/createCaseConfig.json
  src/test/end-to-end/pages/createCasePages/createCaseConfig.json
  src/test/end-to-end/pages/createCasePages/page1initiateCase1.js
  src/test/end-to-end/pages/createCasePages/page2claimantDetails.js
  src/test/end-to-end/pages/createCasePages/page3RespondentsDetails.js
  src/test/end-to-end/pages/createCasePages/page4claimantWorkAddressDetails.js
  src/test/end-to-end/pages/createCasePages/page5ClaimantOtherDetails.js
  src/test/end-to-end/pages/createCasePages/page6BroughtForwardDates.js
  src/test/end-to-end/pages/createCasePages/page7claimantRepresented.js
  src/test/end-to-end/pages/createCasePages/page8UploadDocumentsPage.js
  src/test/end-to-end/pages/createCasePages/page9SubmitPage.js
  src/test/end-to-end/pages/newCase/newCase.js
  src/test/end-to-end/pages/newCase/newCaseConfig.json
  src/test/end-to-end/pages/steps.js
  src/test/end-to-end/paths/manchester-Individual.js
  src/test/end-to-end/paths/scotland-Individual.js
  src/test/end-to-end/paths/verifyLeedsCasePrintHearingLists.js
  src/test/end-to-end/paths/verifyManchesterCasePrintHearingLists.js
Labels: ns:ethos, prd:ethos, ecm-automation-phase2, rel:ethos-repl-docmosis-backend-pr-1860

#1861 [ECM-700] Accessibility Testing
  src/test/end-to-end/helpers/PuppeteerHelper.js
  src/test/end-to-end/helpers/WebDriverHelper.js
  src/test/end-to-end/helpers/accessibility.js
  src/test/end-to-end/pages/acceptanceCase/acceptCase.js
  src/test/end-to-end/pages/acceptanceCase/rejectCase.js
Labels: ns:ethos, prd:ethos, ecm-automation-phase2, rel:ethos-repl-docmosis-backend-pr-1861
