Repository hmcts/ethos-repl-docmosis-service, pull requests merged in 2023-11, with the labels that each got.

#2147 Update LondonC address
  src/main/resources/defaults.yml
  src/test/end-to-end/data/commonConfig.json
Labels: ns:ethos, prd:ethos, rel:ethos-repl-docmosis-backend-pr-2147

#2138 Ecm 1429
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TribunalOfficesService.java
  src/main/resources/defaults.yml
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/DefaultValuesReaderServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/TribunalOfficeServiceTest.java
  src/test/resources/defaults.yml
Labels: ns:ethos, prd:ethos, rel:ethos-repl-docmosis-backend-pr-2138

#2151 Postgres Flexi DB subnet
  infrastructure/database-flexi.tf
Labels: ns:ethos, prd:ethos, destroy, rel:ethos-repl-docmosis-backend-pr-2151

#2156 CVEs
  config/owasp/suppressions.xml
  yarn.lock
Labels: ns:ethos, prd:ethos, rel:ethos-repl-docmosis-backend-pr-2156

#2139 ecm-data-model version updated
  build.gradle
  config/owasp/suppressions.xml
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/DefaultValuesReaderServiceTest.java
  src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/ReferenceServiceTest.java
  yarn-audit-known-issues
Labels: ns:ethos, prd:ethos, destroy, rel:ethos-repl-docmosis-backend-pr-2139

#2161 Allow ECM to run on cftlib alongside ET
  src/main/resources/application-cftlib.properties
Labels: ns:ethos, prd:ethos, rel:ethos-repl-docmosis-backend-pr-2161
