Repository hmcts/ethos-repl-docmosis-service, pull requests merged in 2023-01, with the labels that each got.

#1995 [EM-1075]-Dependency Check Fix
  build.gradle
  config/owasp/suppressions.xml
  src/test/end-to-end/codecept.conf.js
Labels: ns:ethos, prd:ethos, ecm-support, rel:ethos-repl-docmosis-backend-pr-1995

#1997 [EM-1083]-Leeds Multiples Case Test Fix
  src/test/config.js
  src/test/end-to-end/data/commonConfig.json
  src/test/end-to-end/helpers/caseHelper.js
  src/test/end-to-end/pages/IDAM/signIn.js
  src/test/end-to-end/pages/createCase/createMultiplesCase.js
  src/test/end-to-end/pages/steps.js
  src/test/end-to-end/paths/acceptCase.js
  src/test/end-to-end/paths/leedsMultiplesCase.js
Labels: ns:ethos, prd:ethos, ecm-automation-phase2, rel:ethos-repl-docmosis-backend-pr-1997

#2003 [ECM-1098]-Dependency Check Fix
  package.json
  yarn.lock
Labels: ns:ethos, prd:ethos, ecm-support, rel:ethos-repl-docmosis-backend-pr-2003

#2002 ECM-1090
  package.json
  src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Helper.java
  yarn.lock
Labels: ns:ethos, prd:ethos, rel:ethos-repl-docmosis-backend-pr-2002

#2005 [ECM-1106]-Manchester Office Scripts Performance
  src/test/end-to-end/paths/manchesterOfficeScenarios.js
  src/test/end-to-end/paths/manchesterOfficeScenarios2.js
  src/test/end-to-end/paths/verifyManchesterCaseAcceptCase.js
  src/test/end-to-end/paths/verifyManchesterCaseAllocateHearing.js
  src/test/end-to-end/paths/verifyManchesterCaseBFAction.js
  src/test/end-to-end/paths/verifyManchesterCaseClaimantDetails.js
  src/test/end-to-end/paths/verifyManchesterCaseClaimantRepresentative.js
  src/test/end-to-end/paths/verifyManchesterCaseDetails.js
  src/test/end-to-end/paths/verifyManchesterCaseHearingDetails.js
  src/test/end-to-end/paths/verifyManchesterCaseJudgment.js
  src/test/end-to-end/paths/verifyManchesterCaseJurisdiction.js
  src/test/end-to-end/paths/verifyManchesterCaseLetters.js
  src/test/end-to-end/paths/verifyManchesterCaseListHearing.js
  src/test/end-to-end/paths/verifyManchesterCasePrintHearingLists.js
  src/test/end-to-end/paths/verifyManchesterCaseRejectCase.js
  src/test/end-to-end/paths/verifyManchesterCaseRespondentDetails.js
  src/test/end-to-end/paths/verifyManchesterCaseRespondentRepresentative.js
  src/test/end-to-end/paths/verifyManchesterCaseRestrictedReporting.js
  src/test/end-to-end/paths/verifyManchesterFixCaseAPI.js
Labels: ns:ethos, prd:ethos, rel:ethos-repl-docmosis-backend-pr-2005

#2006 [ECM-1108]-Dependency Check Fix
  package.json
  src/test/end-to-end/codecept.conf.js
  src/test/end-to-end/helpers/caseHelper.js
  src/test/end-to-end/pages/allocateHearing/allocateHearing.js
  src/test/end-to-end/pages/nextStep/nextStep.js
  src/test/end-to-end/paths/manchesterOfficeScenarios.js
  src/test/end-to-end/paths/manchesterOfficeScenarios2.js
  yarn.lock
Labels: ns:ethos, prd:ethos, ecm-support, rel:ethos-repl-docmosis-backend-pr-2006

#2007 [ECM-1109]-Leeds Office Automation Scripts Performance Issue Fix
  src/test/end-to-end/paths/leedsOfficeSingles.js
  src/test/end-to-end/paths/leedsOfficeSingles2.js
  src/test/end-to-end/paths/manchesterOfficeScenarios.js
  src/test/end-to-end/paths/manchesterOfficeScenarios2.js
  src/test/end-to-end/paths/verifyBFAction.js
  src/test/end-to-end/paths/verifyCaseClose.js
  src/test/end-to-end/paths/verifyCaseDetails.js
  src/test/end-to-end/paths/verifyClaimantDetails.js
  src/test/end-to-end/paths/verifyClaimantRepresentative.js
  src/test/end-to-end/paths/verifyFixCaseAPI.js
  src/test/end-to-end/paths/verifyJurisdiction.js
  src/test/end-to-end/paths/verifyLeedsCaseAllocateHearing.js
  src/test/end-to-end/paths/verifyLeedsCaseHearingDetails.js
  src/test/end-to-end/paths/verifyLeedsCaseJudgment.js
  src/test/end-to-end/paths/verifyLeedsCaseListHearing.js
  src/test/end-to-end/paths/verifyLeedsCaseTransfer.js
  src/test/end-to-end/paths/verifyLetters.js
  src/test/end-to-end/paths/verifyRejectCase.js
  src/test/end-to-end/paths/verifyRespondentDetails.js
  src/test/end-to-end/paths/verifyRespondentRepresentative.js
  src/test/end-to-end/paths/verifyRestrictedReporting.js
Labels: ns:ethos, prd:ethos, ecm-automation-phase2, rel:ethos-repl-docmosis-backend-pr-2007
